### ISSUE TITLE
Contact Form - Thank You Page

### ISSUE THREAD

**Issue by marisamorby** [jlengstorf/marisamorby.com#9]
When someone contacts me, the thank you page still has the original text, in addition to the thank you information. I would like for the page to only display the thank you information, because it's confusing. 
Here is the screenshot: 
![screen shot 2016-05-20 at 2 19 07 pm](https://cloud.githubusercontent.com/assets/13393126/15427559/3d4f4082-1e96-11e6-981e-9ba6849df68f.png)

**Comment by jlengstorf** [comment]
@marisamorby This is done. I created a new page, and edited the form to send people to that page rather than displaying a message. You can edit this if you want through the dashboard.
